### ISSUE TITLE
Error find_package(serial REQUIRED)

### ISSUE THREAD

**Issue by LuisYordano** [GeorgeNegret/My_Gripper#1]
Hi @GeorgeNegret.

When I compile the My_Gripper package, I get an error from the serial package:

------------------------
--- stderr: wifi_gripper_driver                         
CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "Findserial.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "serial", but
  CMake did not find one.

  Could not find a package configuration file provided by "serial" with any
  of the following names:

    serialConfig.cmake
    serial-config.cmake

  Add the installation prefix of "serial" to CMAKE_PREFIX_PATH or set
  "serial_DIR" to a directory containing one of the above files.  If "serial"
  provides a separate development package or SDK, be sure it has been
  installed.

---------------------

![serial_error](https://github.com/GeorgeNegret/My_Gripper/assets/13818395/586adbee-d960-435b-a330-10365cc4b087)

------------------------

Could you indicate the command or link to correctly install the serial package.

I thank you in advance for your answer.

**Comment by wheelbot-tech** [comment]
the Serial package is no longer needed ,
I have updated wifi_gripper_driver

**Comment by LuisYordano** [comment]
Now when I run the commands the following happens:

-----------
### micro-ros-agent udp4 -p 9999 -v6 (everything correct)

![1](https://github.com/GeorgeNegret/My_Gripper/assets/13818395/2bb55a35-796d-48a6-96d3-f15e89aa2e3d)
-----------
### ros2 launch wifi_gripper_driver wifi_gripper_control.launch.py (everything correct)

![2](https://github.com/GeorgeNegret/My_Gripper/assets/13818395/37ded2bb-f863-465a-bd30-b8b67cef75b0)
![3](https://github.com/GeorgeNegret/My_Gripper/assets/13818395/241f1d50-ae35-4755-86a8-85e6192a13c9)
-----------
### ros2 launch my_gripper_moveit_config ur_wifi_gripper_moveit.launch.py ur_type:=ur10e

![4](https://github.com/GeorgeNegret/My_Gripper/assets/13818395/7ebabcf5-34a9-4bb3-92a2-afecc012ca94)

-----------------

The package does not exist : **ur_moveit_config**

-----------------

You could update your repository with the missing packages or files.

I thank you in advance for your answer.

**Comment by wheelbot-tech** [comment]
To run the my gripper on Moveit you need to launch wifi_gripper_moveit.launch.py .

To run UR robot with the my gripper attached (ur_wifi_gripper_moveit.launch.py ) you need to install : https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver.git

**Comment by LuisYordano** [comment]
Thanks @GeorgeNegret.
